### PR TITLE
Support monorepo

### PR DESCRIPTION
**Pull request by mickmister**
#### Summary

[Open in Gitpod](https://github.com/mattermost/mattermost-gitpod-config/pull/32)

### CODE REVIEW

**Comment by sinansonmez** [comment]
@mickmister thanks for the PR. As the monorepo migration is completed, can we merge this?

**Comment by mickmister** [comment]
@sinansonmez Thanks for following up here. There are some final additions I need to do now. I think I can have this done today

**Comment by mickmister** [comment]
@sinansonmez This should be good to merge now. Please try it out and see if you run into any issues :+1:

**Comment by sinansonmez** [comment]
Thanks @mickmister i will test today

**Pull request merged**
